HOST: http://api.trailsafeapp.com/

--- API Version 1 ---
---
This is the trailsafe API.
---

--
Device Root
The following is what the device has access to at it's root.
--
Shows the resources available to the device and thier respective urls
GET /
> Content-Type: application/json
> Device-ID: {device uuid}
> Authorization: {api key}
< 200
< Content-Type: application/json
{
    "current_activity": "/current_activity",
    "current_help_request": "/current_help_request",
    "user": "/user"
}

-- User --
Create the User for this device
POST /user
> Content-Type: application/json
> Device-ID: {device uuid}
> Authorization: {api key}
{ "user": {
    "first_name":   "Bob",
    "last_name":    "Yetiman",
    "phone_number": "(555) 555-1234"
  }
}
< 201
{ "user": {
    "first_name":   "Bob",
    "last_name":    "Yetiman",
    "phone_number": "(555) 555-1234"
  }
}