FORMAT: X-1A

# Trailsafe API

# Group Device

## Root [/ ]

### Device Root [GET]

The Device root holds all the information for a device.

+ Request Create Message (application/json)
  
  This is our first request named `Create Message`.

    + Headers

            X-My-Request-Header: 42
    
    + Body
        
            { "message" : "A message to be posted." }

    + Schema

            { ... }    
        
+ Response 201 (text/plain)
        
        Created.
