defaults: &defaults
  host: localhost
  adapter: postgis
  encoding: unicode
  pool: 5
  username: trailsafe
  password:

development:
  <<: *defaults
  database: trailsafe_server_development

test:
  <<: *defaults
  database: trailsafe_server_test
