defaults: &defaults
  host: localhost
  adapter: postgis
  encoding: unicode
  postgis_extension: true
  schema_search_path: public,postgis
  pool: 5
  username: trailsafe
  su_username: jwaldrip

development:
  <<: *defaults
  database: trailsafe_server_development

test:
  <<: *defaults
  database: trailsafe_server_test
